name: Apply Terraform
on:
  push:
    branches:
      - main

jobs:
  platform:
    name: 'Terraform Apply - Platform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init - Platform
        run: terraform init

      - name: Terraform Apply - Platform
        run: terraform apply -auto-approve -var-file="platform.tfvars"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  swing:
    name: 'Terraform Apply - Swing Analyzer'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/swing-analyzer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Swing)
        run: terraform init

      - name: Terraform Apply (Swing)
        run: terraform apply -auto-approve -var-file="swing-analyzer.tfvars"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}